import { test, expect, type Page } from '@playwright/test'

async function ready(page: Page) {
  await page.goto('/')
  await page.waitForFunction(() => {
    const canvas = document.querySelector('canvas')
    return canvas && canvas.getContext('2d')!.getImageData(10, 10, 1, 1).data[3]! > 0
  })
  await page.evaluate(() => document.fonts.ready)
}

test('desktop expedition, keyboard controls, pause, guide, map, settings and restart', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1440, height: 1100 })
  await ready(page)
  await expect(page).toHaveTitle(/Pitfall!/)
  await expect(page.locator('.time-score strong')).toHaveText('20:00')
  await expect(page.locator('.main-score strong')).toHaveText('002000')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/desktop-ready.png', fullPage: true })
  await page.getByRole('button', { name: 'Start expedition' }).click()
  await expect(page.locator('.start-overlay')).toHaveCount(0)
  await page.keyboard.down('ArrowRight')
  await page.waitForTimeout(1100)
  await page.keyboard.press('Space')
  await expect(page.locator('.scene-number')).toHaveText('002', { timeout: 12000 })
  await page.keyboard.up('ArrowRight')
  await expect(page.locator('.scene-number')).toHaveText('002')
  await page.screenshot({ path: 'test-results/desktop-playing.png', fullPage: true })
  await page.keyboard.press('p')
  await expect(page.getByRole('button', { name: 'Keep exploring' })).toBeVisible()
  const frozenTime = await page.locator('.time-score strong').textContent()
  await page.waitForTimeout(1100)
  await expect(page.locator('.time-score strong')).toHaveText(frozenTime!)
  await page.getByRole('button', { name: 'Field guide', exact: false }).first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Keep exploring' })).toBeVisible()
  await page.getByRole('button', { name: 'Trail map' }).click()
  await expect(page.locator('.trail-map>div')).toHaveCount(255)
  await expect(page.locator('.trail-map .explored')).toHaveCount(2)
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.getByRole('button', { name: 'Keep exploring' }).click()
  await page.getByRole('button', { name: 'Classic', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Classic', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.screenshot({ path: 'test-results/desktop-classic.png', fullPage: true })
  await page.getByRole('button', { name: 'Mute sound', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Classic', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Enable sound', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Start expedition' }).click()
  await page.keyboard.press('p')
  await page.getByRole('button', { name: 'Start a new expedition' }).click()
  await expect(page.locator('.scene-number')).toHaveText('001')
  await expect(page.locator('.main-score strong')).toHaveText('002000')
  await page.getByRole('button', { name: 'Trail map' }).click()
  await expect(page.locator('.session-label')).toHaveText('TAKING A BREATHER')
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await expect(page.locator('.session-label')).toHaveText('IN PROGRESS')
  await page.evaluate(() => window.dispatchEvent(new Event('blur')))
  await expect(page.getByRole('button', { name: 'Keep exploring' })).toBeVisible()
  for (const width of [320, 768, 1920]) {
    await page.setViewportSize({ width, height: 1080 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `overflow at ${width}px`).toBe(true)
  }
  expect(errors).toEqual([])
})

test('mobile layout and simultaneous touch movement and jump', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 })
  const page = await context.newPage()
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await ready(page)
  await expect(page.locator('.touch-controls')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/mobile-ready.png', fullPage: true })
  await page.getByRole('button', { name: 'Start expedition' }).tap()
  const right = await page.getByRole('button', { name: 'Move right', exact: true }).boundingBox()
  const jump = await page.getByRole('button', { name: 'Jump or release vine', exact: true }).boundingBox()
  const client = await context.newCDPSession(page)
  const point = (r: NonNullable<typeof right>, id: number) => ({ x: r.x + r.width / 2, y: r.y + r.height / 2, id })
  await client.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [point(right!, 1)] })
  await page.waitForTimeout(1100)
  await client.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [point(right!, 1), point(jump!, 2)] })
  await expect(page.locator('.scene-number')).toHaveText('002', { timeout: 12000 })
  await client.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(page.locator('.scene-number')).toHaveText('002')
  await page.getByRole('button', { name: 'Pause expedition', exact: true }).tap()
  await expect(page.getByRole('button', { name: 'Keep exploring' })).toBeVisible()
  await page.screenshot({ path: 'test-results/mobile-paused.png', fullPage: true })
  expect(errors).toEqual([])
  await context.close()
})
